old_at0: main.c
	clang main.c -o ~/.local/bin/old_at0 -O0 -g -Wall -Wextra -Wpedantic -Wshadow -Wno-gnu-empty-struct -Wenum-compare -Wenum-compare-switch -Wenum-conversion -Wenum-enum-conversion -march=native -fPIE -fno-color-diagnostics
